**Import Libraries**

In [65]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the dataset**

In [66]:
dataset = pd.read_csv('./Social_Network_Ads_log_reg.csv')
gendermap = {'Male':0,'Female':1}
dataset['Gender']=dataset['Gender'].map(gendermap)
dataset2 = dataset.copy()
dataset2 = dataset.drop(['Purchased'], axis=1)



X = dataset2.iloc[:,1:].values
y = dataset.iloc[:, 4].values

**label Encoding**

In [67]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

**Splitting the dataset into the Training set and Test set**

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [69]:
print(X_train)

[[     1     44  39000]
 [     0     32 120000]
 [     1     38  50000]
 [     1     32 135000]
 [     1     52  21000]
 [     1     53 104000]
 [     0     39  42000]
 [     0     38  61000]
 [     1     36  50000]
 [     1     36  63000]
 [     1     35  25000]
 [     0     35  50000]
 [     0     42  73000]
 [     1     47  49000]
 [     1     59  29000]
 [     0     49  65000]
 [     1     45 131000]
 [     1     31  89000]
 [     1     46  82000]
 [     1     47  51000]
 [     0     26  15000]
 [     0     60 102000]
 [     1     38 112000]
 [     0     40 107000]
 [     1     42  53000]
 [     0     35  59000]
 [     0     48  41000]
 [     1     48 134000]
 [     1     38 113000]
 [     0     29 148000]
 [     1     26  15000]
 [     0     60  42000]
 [     0     24  19000]
 [     0     42 149000]
 [     1     46  96000]
 [     0     28  59000]
 [     0     39  96000]
 [     0     28  89000]
 [     0     41  72000]
 [     0     45  26000]
 [     1     33  69000]
 [     1     20 

In [70]:
print(y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [71]:
print(X_test)

[[     0     30  87000]
 [     1     38  50000]
 [     0     35  75000]
 [     1     30  79000]
 [     1     35  50000]
 [     0     27  20000]
 [     1     31  15000]
 [     0     36 144000]
 [     1     18  68000]
 [     0     47  43000]
 [     0     30  49000]
 [     1     28  55000]
 [     0     37  55000]
 [     0     39  77000]
 [     0     20  86000]
 [     1     32 117000]
 [     0     37  77000]
 [     0     19  85000]
 [     1     55 130000]
 [     0     35  22000]
 [     1     35  47000]
 [     1     47 144000]
 [     1     41  51000]
 [     0     47 105000]
 [     1     23  28000]
 [     1     49 141000]
 [     1     28  87000]
 [     0     29  80000]
 [     1     37  62000]
 [     1     32  86000]
 [     0     21  88000]
 [     0     37  79000]
 [     0     57  60000]
 [     0     37  53000]
 [     0     24  58000]
 [     0     18  52000]
 [     0     22  81000]
 [     1     34  43000]
 [     1     31  34000]
 [     1     49  36000]
 [     0     27  88000]
 [     0     41 

In [72]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


**Feature Scaling**

In [73]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [74]:
print(X_train)

[[ 0.98019606  0.58164944 -0.88670699]
 [-1.02020406 -0.60673761  1.46173768]
 [ 0.98019606 -0.01254409 -0.5677824 ]
 [ 0.98019606 -0.60673761  1.89663484]
 [ 0.98019606  1.37390747 -1.40858358]
 [ 0.98019606  1.47293972  0.99784738]
 [-1.02020406  0.08648817 -0.79972756]
 [-1.02020406 -0.01254409 -0.24885782]
 [ 0.98019606 -0.21060859 -0.5677824 ]
 [ 0.98019606 -0.21060859 -0.19087153]
 [ 0.98019606 -0.30964085 -1.29261101]
 [-1.02020406 -0.30964085 -0.5677824 ]
 [-1.02020406  0.38358493  0.09905991]
 [ 0.98019606  0.8787462  -0.59677555]
 [ 0.98019606  2.06713324 -1.17663843]
 [-1.02020406  1.07681071 -0.13288524]
 [ 0.98019606  0.68068169  1.78066227]
 [ 0.98019606 -0.70576986  0.56295021]
 [ 0.98019606  0.77971394  0.35999821]
 [ 0.98019606  0.8787462  -0.53878926]
 [-1.02020406 -1.20093113 -1.58254245]
 [-1.02020406  2.1661655   0.93986109]
 [ 0.98019606 -0.01254409  1.22979253]
 [-1.02020406  0.18552042  1.08482681]
 [ 0.98019606  0.38358493 -0.48080297]
 [-1.02020406 -0.30964085

In [75]:
print(X_test)

[[-1.02020406 -0.80480212  0.50496393]
 [ 0.98019606 -0.01254409 -0.5677824 ]
 [-1.02020406 -0.30964085  0.1570462 ]
 [ 0.98019606 -0.80480212  0.27301877]
 [ 0.98019606 -0.30964085 -0.5677824 ]
 [-1.02020406 -1.10189888 -1.43757673]
 [ 0.98019606 -0.70576986 -1.58254245]
 [-1.02020406 -0.21060859  2.15757314]
 [ 0.98019606 -1.99318916 -0.04590581]
 [-1.02020406  0.8787462  -0.77073441]
 [-1.02020406 -0.80480212 -0.59677555]
 [ 0.98019606 -1.00286662 -0.42281668]
 [-1.02020406 -0.11157634 -0.42281668]
 [-1.02020406  0.08648817  0.21503249]
 [-1.02020406 -1.79512465  0.47597078]
 [ 0.98019606 -0.60673761  1.37475825]
 [-1.02020406 -0.11157634  0.21503249]
 [-1.02020406 -1.89415691  0.44697764]
 [ 0.98019606  1.67100423  1.75166912]
 [-1.02020406 -0.30964085 -1.37959044]
 [ 0.98019606 -0.30964085 -0.65476184]
 [ 0.98019606  0.8787462   2.15757314]
 [ 0.98019606  0.28455268 -0.53878926]
 [-1.02020406  0.8787462   1.02684052]
 [ 0.98019606 -1.49802789 -1.20563157]
 [ 0.98019606  1.07681071

**Training Model on the Training set**

In [76]:
#fitting the regression model to the training set
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

**Predicting the Test set results**

In [77]:
y_pred=regressor.predict(X_test)

In [78]:
print(y_pred)

[ 0.2208572   0.29071286  0.30769543  0.18972007  0.21072947 -0.11856922
 -0.03144498  0.60154415 -0.17280858  0.50371587  0.0737104   0.043463
  0.283572    0.4220845  -0.04962637  0.39018912  0.36876225 -0.08015978
  1.05373475  0.10246437  0.19911262  0.89465771  0.37456853  0.74379748
 -0.19439431  0.93636311  0.16737609  0.16709008  0.31051914  0.27014832
 -0.01522067  0.37650682  0.83615597  0.27582743 -0.05140581 -0.23460628
 -0.01566553  0.15696236  0.04212842  0.52977329  0.1447461   0.37859966
  0.12909811  0.0947198   0.66410011  0.02841873  0.38022025  0.81886001
 -0.10650751  0.72354634  1.07607874  0.08726125  0.23783546  0.43592566
  0.99774334  0.40779849  0.17854808  0.08694785  0.49895386 -0.22521373
  0.00699185  0.84643824 -0.11501033  0.42729137 -0.30878339  1.00520189
  0.06847615  0.02857757  0.33257711  0.47480305  0.5179745   0.31528114
 -0.08552549  0.36907565  0.14861838 -0.11843776  0.50965361  0.38275795
  0.62867323  0.7513832   1.18808896  0.97838191 -0.0

In [85]:
nr0 = 0
nr1=0
purchase0=[]
purchase1=[]
for i in y_pred:
    if i>0.75:
        nr1=nr1+1
        purchase1.append(i)
        dataset['o/p']=1
    else:
        nr0=nr0+1
        purchase0.append(i)
        dataset['o/p']=0
print(purchase)
print(nr,len(y_pred))


[1.0537347548661782, 0.8946577099041704, 0.936363113177525, 0.8361559748993282, 0.8188600090322462, 1.076078737811005, 0.9977433350474856, 0.8464382449223347, 1.0052018916162648, 0.7513831994730626, 1.1880889641538357, 0.9783819147189576, 0.777468004026969, 1.160538114969193, 1.0537347548661782, 0.8946577099041704, 0.936363113177525, 0.8361559748993282, 0.8188600090322462, 1.076078737811005, 0.9977433350474856, 0.8464382449223347, 1.0052018916162648, 0.7513831994730626, 1.1880889641538357, 0.9783819147189576, 0.777468004026969, 1.160538114969193, 1.0537347548661782, 0.8946577099041704, 0.936363113177525, 0.8361559748993282, 0.8188600090322462, 1.076078737811005, 0.9977433350474856, 0.8464382449223347, 1.0052018916162648, 0.7513831994730626, 1.1880889641538357, 0.9783819147189576, 0.777468004026969, 1.160538114969193]
28 100


In [86]:
for i in dataset['o/p']:
    if(i==1):
        print(i)

In [87]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased  o/p
0  15624510       0   19            19000          0    0
1  15810944       0   35            20000          0    0
2  15668575       1   26            43000          0    0
3  15603246       1   27            57000          0    0
4  15804002       0   19            76000          0    0

In [82]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print(cm)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

**Confusion Matrix and Accuracy**

In [30]:
# #visualising the results of the training set
# import matplotlib.pyplot as plt
# plt.scatter(X_train,y_train,color="red")
# plt.plot(X_train,regressor.predict(X_train),color="blue")
# plt.title("Linear Regression Model For Training Set")
# plt.xlabel("Years of Experience")
# plt.ylabel("Salary")
# plt.show()

In [31]:
# #visualising the results of the test set
# import matplotlib.pyplot as plt
# plt.scatter(X_test,y_test,color="red")
# # we observe that the test line and the train line are coincident ,
# # that is simply because we have used the same linear regression model
# plt.plot(X_train,regressor.predict(X_train),color="blue")
# plt.plot(X_test,y_pred,color="green")
# plt.title("Linear Regression Model For Test Set")
# plt.xlabel("Years of Experience")
# plt.ylabel("Salary")
# plt.show()