In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
dataset = pd.read_csv('./Social_Network_Ads_log_reg.csv')
gendermap = {'Male':0,'Female':1}
dataset['Gender']=dataset['Gender'].map(gendermap)
dataset2 = dataset.copy()
dataset2 = dataset.drop(['Purchased'], axis=1)



X = dataset2.iloc[:,1:].values
y = dataset.iloc[:, 4].values

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
print(X_train)

[[     1     44  39000]
 [     0     32 120000]
 [     1     38  50000]
 [     1     32 135000]
 [     1     52  21000]
 [     1     53 104000]
 [     0     39  42000]
 [     0     38  61000]
 [     1     36  50000]
 [     1     36  63000]
 [     1     35  25000]
 [     0     35  50000]
 [     0     42  73000]
 [     1     47  49000]
 [     1     59  29000]
 [     0     49  65000]
 [     1     45 131000]
 [     1     31  89000]
 [     1     46  82000]
 [     1     47  51000]
 [     0     26  15000]
 [     0     60 102000]
 [     1     38 112000]
 [     0     40 107000]
 [     1     42  53000]
 [     0     35  59000]
 [     0     48  41000]
 [     1     48 134000]
 [     1     38 113000]
 [     0     29 148000]
 [     1     26  15000]
 [     0     60  42000]
 [     0     24  19000]
 [     0     42 149000]
 [     1     46  96000]
 [     0     28  59000]
 [     0     39  96000]
 [     0     28  89000]
 [     0     41  72000]
 [     0     45  26000]
 [     1     33  69000]
 [     1     20 

In [6]:
print(y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [7]:
print(X_test)

[[     0     30  87000]
 [     1     38  50000]
 [     0     35  75000]
 [     1     30  79000]
 [     1     35  50000]
 [     0     27  20000]
 [     1     31  15000]
 [     0     36 144000]
 [     1     18  68000]
 [     0     47  43000]
 [     0     30  49000]
 [     1     28  55000]
 [     0     37  55000]
 [     0     39  77000]
 [     0     20  86000]
 [     1     32 117000]
 [     0     37  77000]
 [     0     19  85000]
 [     1     55 130000]
 [     0     35  22000]
 [     1     35  47000]
 [     1     47 144000]
 [     1     41  51000]
 [     0     47 105000]
 [     1     23  28000]
 [     1     49 141000]
 [     1     28  87000]
 [     0     29  80000]
 [     1     37  62000]
 [     1     32  86000]
 [     0     21  88000]
 [     0     37  79000]
 [     0     57  60000]
 [     0     37  53000]
 [     0     24  58000]
 [     0     18  52000]
 [     0     22  81000]
 [     1     34  43000]
 [     1     31  34000]
 [     1     49  36000]
 [     0     27  88000]
 [     0     41 

In [8]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [9]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)
#y consists of categorical values so we do not need to scale it


In [10]:
#Building the classifier
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)

#testing on the test set
y_pred=classifier.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
pred_true=cm[0,0]+cm[1,1]
pred_false=cm[0,1]+cm[1,0]
print("correct predictions:"+str(pred_true))
print("incorrect predictions:"+str(pred_false))
print(cm)


correct predictions:91
incorrect predictions:9
[[66  2]
 [ 7 25]]


In [15]:
#visualising the training set results
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
'''meshgrid forms a grid or a matrix of all the pixels displayed on the screen  '''
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
'''
this function makes a countour between the red and the green , 
it paints the pixels in the region in the graph as red and green according to the prediction 
'''
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.50, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Naive Bayes (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

In [16]:
#visualising the test set results 
from matplotlib.colors import ListedColormap
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.50, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Naive Bayes (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()