**Import Libraries**

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the dataset**

In [3]:
dataset = pd.read_csv('./Social_Network_Ads_log_reg.csv')
gendermap = {'Male':0,'Female':1}
dataset['Gender']=dataset['Gender'].map(gendermap)
dataset2 = dataset.copy()
dataset2 = dataset.drop(['Purchased'], axis=1)



X = dataset2.iloc[:,1:].values
y = dataset.iloc[:, 4].values

**label Encoding**

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

**Splitting the dataset into the Training set and Test set**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

[[     1     44  39000]
 [     0     32 120000]
 [     1     38  50000]
 [     1     32 135000]
 [     1     52  21000]
 [     1     53 104000]
 [     0     39  42000]
 [     0     38  61000]
 [     1     36  50000]
 [     1     36  63000]
 [     1     35  25000]
 [     0     35  50000]
 [     0     42  73000]
 [     1     47  49000]
 [     1     59  29000]
 [     0     49  65000]
 [     1     45 131000]
 [     1     31  89000]
 [     1     46  82000]
 [     1     47  51000]
 [     0     26  15000]
 [     0     60 102000]
 [     1     38 112000]
 [     0     40 107000]
 [     1     42  53000]
 [     0     35  59000]
 [     0     48  41000]
 [     1     48 134000]
 [     1     38 113000]
 [     0     29 148000]
 [     1     26  15000]
 [     0     60  42000]
 [     0     24  19000]
 [     0     42 149000]
 [     1     46  96000]
 [     0     28  59000]
 [     0     39  96000]
 [     0     28  89000]
 [     0     41  72000]
 [     0     45  26000]
 [     1     33  69000]
 [     1     20 

In [7]:
print(y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [8]:
print(X_test)

[[     0     30  87000]
 [     1     38  50000]
 [     0     35  75000]
 [     1     30  79000]
 [     1     35  50000]
 [     0     27  20000]
 [     1     31  15000]
 [     0     36 144000]
 [     1     18  68000]
 [     0     47  43000]
 [     0     30  49000]
 [     1     28  55000]
 [     0     37  55000]
 [     0     39  77000]
 [     0     20  86000]
 [     1     32 117000]
 [     0     37  77000]
 [     0     19  85000]
 [     1     55 130000]
 [     0     35  22000]
 [     1     35  47000]
 [     1     47 144000]
 [     1     41  51000]
 [     0     47 105000]
 [     1     23  28000]
 [     1     49 141000]
 [     1     28  87000]
 [     0     29  80000]
 [     1     37  62000]
 [     1     32  86000]
 [     0     21  88000]
 [     0     37  79000]
 [     0     57  60000]
 [     0     37  53000]
 [     0     24  58000]
 [     0     18  52000]
 [     0     22  81000]
 [     1     34  43000]
 [     1     31  34000]
 [     1     49  36000]
 [     0     27  88000]
 [     0     41 

In [9]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


**Feature Scaling**

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[ 0.98019606  0.58164944 -0.88670699]
 [-1.02020406 -0.60673761  1.46173768]
 [ 0.98019606 -0.01254409 -0.5677824 ]
 [ 0.98019606 -0.60673761  1.89663484]
 [ 0.98019606  1.37390747 -1.40858358]
 [ 0.98019606  1.47293972  0.99784738]
 [-1.02020406  0.08648817 -0.79972756]
 [-1.02020406 -0.01254409 -0.24885782]
 [ 0.98019606 -0.21060859 -0.5677824 ]
 [ 0.98019606 -0.21060859 -0.19087153]
 [ 0.98019606 -0.30964085 -1.29261101]
 [-1.02020406 -0.30964085 -0.5677824 ]
 [-1.02020406  0.38358493  0.09905991]
 [ 0.98019606  0.8787462  -0.59677555]
 [ 0.98019606  2.06713324 -1.17663843]
 [-1.02020406  1.07681071 -0.13288524]
 [ 0.98019606  0.68068169  1.78066227]
 [ 0.98019606 -0.70576986  0.56295021]
 [ 0.98019606  0.77971394  0.35999821]
 [ 0.98019606  0.8787462  -0.53878926]
 [-1.02020406 -1.20093113 -1.58254245]
 [-1.02020406  2.1661655   0.93986109]
 [ 0.98019606 -0.01254409  1.22979253]
 [-1.02020406  0.18552042  1.08482681]
 [ 0.98019606  0.38358493 -0.48080297]
 [-1.02020406 -0.30964085

In [12]:
print(X_test)

[[-1.02020406 -0.80480212  0.50496393]
 [ 0.98019606 -0.01254409 -0.5677824 ]
 [-1.02020406 -0.30964085  0.1570462 ]
 [ 0.98019606 -0.80480212  0.27301877]
 [ 0.98019606 -0.30964085 -0.5677824 ]
 [-1.02020406 -1.10189888 -1.43757673]
 [ 0.98019606 -0.70576986 -1.58254245]
 [-1.02020406 -0.21060859  2.15757314]
 [ 0.98019606 -1.99318916 -0.04590581]
 [-1.02020406  0.8787462  -0.77073441]
 [-1.02020406 -0.80480212 -0.59677555]
 [ 0.98019606 -1.00286662 -0.42281668]
 [-1.02020406 -0.11157634 -0.42281668]
 [-1.02020406  0.08648817  0.21503249]
 [-1.02020406 -1.79512465  0.47597078]
 [ 0.98019606 -0.60673761  1.37475825]
 [-1.02020406 -0.11157634  0.21503249]
 [-1.02020406 -1.89415691  0.44697764]
 [ 0.98019606  1.67100423  1.75166912]
 [-1.02020406 -0.30964085 -1.37959044]
 [ 0.98019606 -0.30964085 -0.65476184]
 [ 0.98019606  0.8787462   2.15757314]
 [ 0.98019606  0.28455268 -0.53878926]
 [-1.02020406  0.8787462   1.02684052]
 [ 0.98019606 -1.49802789 -1.20563157]
 [ 0.98019606  1.07681071

**Training Model on the Training set**

In [13]:
from sklearn.ensemble import RandomForestClassifier
clf1=RandomForestClassifier(n_estimators=2000,criterion='entropy',random_state=1,n_jobs=-1,oob_score=True)
clf1.fit(X_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=2000, n_jobs=-1,
                       oob_score=True, random_state=1)

**Predicting the Test set results**

In [14]:
y_pred=clf1.predict(X_test)

**Confusion Matrix and Accuracy**

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
pred_true=cm[0,0]+cm[1,1]
pred_false=cm[0,1]+cm[1,0]
print("correct predictions:"+str(pred_true))
print("incorrect predictions:"+str(pred_false))

correct predictions:92
incorrect predictions:8


In [16]:
cm

array([[64,  4],
       [ 4, 28]])